language: ruby
script: "bundle exec rake"
rvm:
  - 2.1.9
before_install:
  - gem install bundler -v '< 2'
env:
  - PUPPET_GEM_VERSION='3.6.2'
matrix:
  allow_failures:
    - env: PUPPET_GEM_VESRION="3.6.2"
